[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  function='price'
  path= '/api/price/:symbol'
  cache='manual'

[[edge_functions]]
  function='news'
  path= '/api/news/:symbol'
  cache='manual'

[[edge_functions]]
  function='financial'
  path= '/api/financial'
  cache='manual'
