export default [
  { label: 'MSFT	Microsoft Corporation', id: 'MSFT' },
  { label: 'AAPL	Apple Inc.', id: 'AAPL' },
  { label: 'NVDA	NVIDIA Corporation', id: 'NVDA' },
  { label: 'GOOGL	Alphabet Inc.', id: 'GOOGL' },
  { label: 'AMZN	Amazon.com, Inc.', id: 'AMZN' },
  { label: 'META	Meta Platforms, Inc.', id: 'META' },
  { label: 'TSLA	Tesla, Inc.', id: 'TSLA' },
  { label: 'BRK-B	Berkshire Hathaway Inc. New', id: 'BRK-B' },
  { label: 'LLY	Eli Lilly and Company', id: 'LLY' },
  { label: 'AVGO	Broadcom Inc.', id: 'AVGO' },
  { label: 'V	Visa Inc.', id: 'V' },
  { label: 'JPM	JP Morgan Chase & Co.', id: 'JPM' },
  { label: 'XOM	Exxon Mobil Corporation', id: 'XOM' },
  { label: 'WMT	Walmart Inc.', id: 'WMT' },
  { label: 'GOOG	Alphabet Inc.', id: 'GOOG' },
  { label: 'UNH	UnitedHealth Group Incorporated', id: 'UNH' },
  { label: 'MA	Mastercard Incorporated', id: 'MA' },
  { label: 'PG	Procter & Gamble Company (The)', id: 'PG' },
  { label: 'JNJ	Johnson & Johnson', id: 'JNJ' },
  { label: 'COST	Costco Wholesale Corporation', id: 'COST' },
  { label: 'HD	Home Depot, Inc. (The)', id: 'HD' },
  { label: 'MRK	Merck & Company, Inc.', id: 'MRK' },
  { label: 'ORCL	Oracle Corporation', id: 'ORCL' },
  { label: 'CVX	Chevron Corporation', id: 'CVX' },
  { label: 'BAC	Bank of America Corporation', id: 'BAC' },
  { label: 'ABBV	AbbVie Inc.', id: 'ABBV' },
  { label: 'KO	Coca-Cola Company (The)', id: 'KO' },
  { label: 'CRM	Salesforce, Inc.', id: 'CRM' },
  { label: 'NFLX	Netflix, Inc.', id: 'NFLX' },
  { label: 'PEP	Pepsico, Inc.', id: 'PEP' },
  { label: 'AMD	Advanced Micro Devices, Inc.', id: 'AMD' },
  { label: 'TMO	Thermo Fisher Scientific Inc', id: 'TMO' },
  { label: 'ADBE	Adobe Inc.', id: 'ADBE' },
  { label: 'WFC	Wells Fargo & Company', id: 'WFC' },
  { label: 'LIN	Linde plc', id: 'LIN' },
  { label: 'QCOM	QUALCOMM Incorporated', id: 'QCOM' },
  { label: "MCD	McDonald's Corporation", id: 'MCD' },
  { label: 'CSCO	Cisco Systems, Inc.', id: 'CSCO' },
  { label: 'DIS	Walt Disney Company (The)', id: 'DIS' },
  { label: 'ACN	Accenture plc', id: 'ACN' },
  { label: 'TMUS	T-Mobile US, Inc.', id: 'TMUS' },
  { label: 'DHR	Danaher Corporation', id: 'DHR' },
  { label: 'ABT	Abbott Laboratories', id: 'ABT' },
  { label: 'GE	GE Aerospace', id: 'GE' },
  { label: 'INTU	Intuit Inc.', id: 'INTU' },
  { label: 'AXP	American Express Company', id: 'AXP' },
  { label: 'AMAT	Applied Materials, Inc.', id: 'AMAT' },
  { label: 'CAT	Caterpillar, Inc.', id: 'CAT' },
  { label: 'TXN	Texas Instruments Incorporated', id: 'TXN' },
  { label: 'VZ	Verizon Communications Inc.', id: 'VZ' },
  { label: 'AMGN	Amgen Inc.', id: 'AMGN' },
  { label: 'MS	Morgan Stanley', id: 'MS' },
  { label: 'PFE	Pfizer, Inc.', id: 'PFE' },
  { label: 'PM	Philip Morris International Inc', id: 'PM' },
  { label: 'CMCSA	Comcast Corporation', id: 'CMCSA' },
  { label: 'IBM	International Business Machines', id: 'IBM' },
  { label: 'NEE	NextEra Energy, Inc.', id: 'NEE' },
  { label: 'UNP	Union Pacific Corporation', id: 'UNP' },
  { label: 'BX	Blackstone Inc.', id: 'BX' },
  { label: 'NOW	ServiceNow, Inc.', id: 'NOW' },
  { label: 'GS	Goldman Sachs Group, Inc. (The)', id: 'GS' },
  { label: 'COP	ConocoPhillips', id: 'COP' },
  { label: 'RTX	RTX Corporation', id: 'RTX' },
  { label: 'UBER	Uber Technologies, Inc.', id: 'UBER' },
  { label: 'SCHW	Charles Schwab Corporation (The', id: 'SCHW' },
  { label: 'NKE	Nike, Inc.', id: 'NKE' },
  { label: 'ISRG	Intuitive Surgical, Inc.', id: 'ISRG' },
  { label: 'SPGI	S&P Global Inc.', id: 'SPGI' },
  { label: "LOW	Lowe's Companies, Inc.", id: 'LOW' },
  { label: 'MU	Micron Technology, Inc.', id: 'MU' },
  { label: 'ETN	Eaton Corporation, PLC', id: 'ETN' },
  { label: 'HON	Honeywell International Inc.', id: 'HON' },
  { label: 'INTC	Intel Corporation', id: 'INTC' },
  { label: 'BKNG	Booking Holdings Inc. Common St', id: 'BKNG' },
  { label: 'PGR	Progressive Corporation (The)', id: 'PGR' },
  { label: 'UPS	United Parcel Service, Inc.', id: 'UPS' },
  { label: 'SYK	Stryker Corporation', id: 'SYK' },
  { label: 'ELV	Elevance Health, Inc.', id: 'ELV' },
  { label: 'T	AT&T Inc.', id: 'T' },
  { label: 'C	Citigroup, Inc.', id: 'C' },
  { label: 'LRCX	Lam Research Corporation', id: 'LRCX' },
  { label: 'BLK	BlackRock, Inc.', id: 'BLK' },
  { label: 'DE	Deere & Company', id: 'DE' },
  { label: 'LMT	Lockheed Martin Corporation', id: 'LMT' },
  { label: 'TJX	TJX Companies, Inc. (The)', id: 'TJX' },
  { label: 'MDT	Medtronic plc.', id: 'MDT' },
  { label: 'BA	Boeing Company (The)', id: 'BA' },
  { label: 'VRTX	Vertex Pharmaceuticals Incorpor', id: 'VRTX' },
  { label: 'BSX	Boston Scientific Corporation', id: 'BSX' },
  { label: 'REGN	Regeneron Pharmaceuticals, Inc.', id: 'REGN' },
  { label: 'CB	Chubb Limited', id: 'CB' },
  { label: 'ADI	Analog Devices, Inc.', id: 'ADI' },
  { label: 'MMC	Marsh & McLennan Companies, Inc', id: 'MMC' },
  { label: 'ADP	Automatic Data Processing, Inc.', id: 'ADP' },
  { label: 'PLD	Prologis, Inc.', id: 'PLD' },
  { label: 'CI	The Cigna Group', id: 'CI' },
  { label: 'ANET	Arista Networks, Inc.', id: 'ANET' },
  { label: 'KLAC	KLA Corporation', id: 'KLAC' },
  { label: 'PANW	Palo Alto Networks, Inc.', id: 'PANW' },
  { label: 'MDLZ	Mondelez International, Inc.', id: 'MDLZ' },
  { label: 'ABNB	Airbnb, Inc.', id: 'ABNB' },
  { label: 'BMY	Bristol-Myers Squibb Company', id: 'BMY' },
  { label: 'FI	Fiserv, Inc.', id: 'FI' },
  { label: 'CMG	Chipotle Mexican Grill, Inc.', id: 'CMG' },
  { label: 'SBUX	Starbucks Corporation', id: 'SBUX' },
  { label: 'AMT	American Tower Corporation (REI', id: 'AMT' },
  { label: 'HCA	HCA Healthcare, Inc.', id: 'HCA' },
  { label: 'SO	Southern Company (The)', id: 'SO' },
  { label: 'SNPS	Synopsys, Inc.', id: 'SNPS' },
  { label: 'WM	Waste Management, Inc.', id: 'WM' },
  { label: 'GILD	Gilead Sciences, Inc.', id: 'GILD' },
  { label: 'SHW	Sherwin-Williams Company (The)', id: 'SHW' },
  { label: 'GD	General Dynamics Corporation', id: 'GD' },
  { label: 'DUK	Duke Energy Corporation (Holdin', id: 'DUK' },
  { label: 'CDNS	Cadence Design Systems, Inc.', id: 'CDNS' },
  { label: 'CL	Colgate-Palmolive Company', id: 'CL' },
  { label: 'ZTS	Zoetis Inc.', id: 'ZTS' },
  { label: 'MO	Altria Group, Inc.', id: 'MO' },
  { label: 'ICE	Intercontinental Exchange Inc.', id: 'ICE' },
  { label: 'APH	Amphenol Corporation', id: 'APH' },
  { label: 'TGT	Target Corporation', id: 'TGT' },
  { label: 'TT	Trane Technologies plc', id: 'TT' },
  { label: 'CME	CME Group Inc.', id: 'CME' },
  { label: 'EOG	EOG Resources, Inc.', id: 'EOG' },
  { label: 'ITW	Illinois Tool Works Inc.', id: 'ITW' },
  { label: 'FCX	Freeport-McMoRan, Inc.', id: 'FCX' },
  { label: 'TDG	Transdigm Group Incorporated', id: 'TDG' },
  { label: "MCO	Moody's Corporation", id: 'MCO' },
  { label: 'MCK	McKesson Corporation', id: 'MCK' },
  { label: 'PH	Parker-Hannifin Corporation', id: 'PH' },
  { label: 'EQIX	Equinix, Inc.', id: 'EQIX' },
  { label: 'CTAS	Cintas Corporation', id: 'CTAS' },
  { label: 'NOC	Northrop Grumman Corporation', id: 'NOC' },
  { label: 'CVS	CVS Health Corporation', id: 'CVS' },
  { label: 'SLB	Schlumberger N.V.', id: 'SLB' },
  { label: 'MAR	Marriott International', id: 'MAR' },
  { label: 'BDX	Becton, Dickinson and Company', id: 'BDX' },
  { label: 'CEG	Constellation Energy Corporatio', id: 'CEG' },
  { label: 'CSX	CSX Corporation', id: 'CSX' },
  { label: 'NXPI	NXP Semiconductors N.V.', id: 'NXPI' },
  { label: 'ECL	Ecolab Inc.', id: 'ECL' },
  { label: 'EMR	Emerson Electric Company', id: 'EMR' },
  { label: 'PYPL	PayPal Holdings, Inc.', id: 'PYPL' },
  { label: 'FDX	FedEx Corporation', id: 'FDX' },
  { label: 'USB	U.S. Bancorp', id: 'USB' },
  { label: 'AON	Aon plc', id: 'AON' },
  { label: 'MPC	Marathon Petroleum Corporation', id: 'MPC' },
  { label: 'PNC	PNC Financial Services Group, I', id: 'PNC' },
  { label: 'PSX	Phillips 66', id: 'PSX' },
  { label: 'MSI	Motorola Solutions, Inc.', id: 'MSI' },
  { label: "ORLY	O'Reilly Automotive, Inc.", id: 'ORLY' },
  { label: 'RSG	Republic Services, Inc.', id: 'RSG' },
  { label: 'WELL	Welltower Inc.', id: 'WELL' },
  { label: 'CARR	Carrier Global Corporation', id: 'CARR' },
  { label: 'MNST	Monster Beverage Corporation', id: 'MNST' },
  { label: 'PCAR	PACCAR Inc.', id: 'PCAR' },
  { label: 'OXY	Occidental Petroleum Corporatio', id: 'OXY' },
  { label: 'ROP	Roper Technologies, Inc.', id: 'ROP' },
  { label: 'APD	Air Products and Chemicals, Inc', id: 'APD' },
  { label: 'SPG	Simon Property Group, Inc.', id: 'SPG' },
  { label: 'AJG	Arthur J. Gallagher & Co.', id: 'AJG' },
  { label: 'MMM	3M Company', id: 'MMM' },
  { label: 'COF	Capital One Financial Corporati', id: 'COF' },
  { label: 'AIG	American International Group, I', id: 'AIG' },
  { label: 'TFC	Truist Financial Corporation', id: 'TFC' },
  { label: 'CPRT	Copart, Inc.', id: 'CPRT' },
  { label: 'EW	Edwards Lifesciences Corporatio', id: 'EW' },
  { label: 'HLT	Hilton Worldwide Holdings Inc.', id: 'HLT' },
  { label: 'NSC	Norfolk Southern Corporation', id: 'NSC' },
  { label: 'MET	MetLife, Inc.', id: 'MET' },
  { label: 'GM	General Motors Company', id: 'GM' },
  { label: 'AZO	AutoZone, Inc.', id: 'AZO' },
  { label: 'VLO	Valero Energy Corporation', id: 'VLO' },
  { label: 'DXCM	DexCom, Inc.', id: 'DXCM' },
  { label: 'TRV	The Travelers Companies, Inc.', id: 'TRV' },
  { label: 'MCHP	Microchip Technology Incorporat', id: 'MCHP' },
  { label: 'HES	Hess Corporation', id: 'HES' },
  { label: 'DHI	D.R. Horton, Inc.', id: 'DHI' },
  { label: 'NEM	Newmont Corporation', id: 'NEM' },
  { label: 'AFL	AFLAC Incorporated', id: 'AFL' },
  { label: 'SRE	DBA Sempra', id: 'SRE' },
  { label: 'PSA	Public Storage', id: 'PSA' },
  { label: 'WMB	Williams Companies, Inc. (The)', id: 'WMB' },
  { label: 'AEP	American Electric Power Company', id: 'AEP' },
  { label: 'STZ	Constellation Brands, Inc.', id: 'STZ' },
  { label: 'O	Realty Income Corporation', id: 'O' },
  { label: 'F	Ford Motor Company', id: 'F' },
  { label: 'EL	Estee Lauder Companies, Inc. (T', id: 'EL' },
  { label: 'GWW	W.W. Grainger, Inc.', id: 'GWW' },
  { label: 'URI	United Rentals, Inc.', id: 'URI' },
  { label: 'SMCI	Super Micro Computer, Inc.', id: 'SMCI' },
  { label: 'OKE	ONEOK, Inc.', id: 'OKE' },
  { label: 'PCG	Pacific Gas & Electric Co.', id: 'PCG' },
  { label: 'ADSK	Autodesk, Inc.', id: 'ADSK' },
  { label: 'KDP	Keurig Dr Pepper Inc.', id: 'KDP' },
  { label: 'KMB	Kimberly-Clark Corporation', id: 'KMB' },
  { label: 'GEV	GE Vernova Inc.', id: 'GEV' },
  { label: 'ALL	Allstate Corporation (The)', id: 'ALL' },
  { label: 'DLR	Digital Realty Trust, Inc.', id: 'DLR' },
  { label: 'MRNA	Moderna, Inc.', id: 'MRNA' },
  { label: 'LEN	Lennar Corporation', id: 'LEN' },
  { label: 'COR	Cencora, Inc.', id: 'COR' },
  { label: 'TEL	TE Connectivity Ltd. New Switze', id: 'TEL' },
  { label: 'ROST	Ross Stores, Inc.', id: 'ROST' },
  { label: 'D	Dominion Energy, Inc.', id: 'D' },
  { label: 'LULU	lululemon athletica inc.', id: 'LULU' },
  { label: 'FTNT	Fortinet, Inc.', id: 'FTNT' },
  { label: 'JCI	Johnson Controls International ', id: 'JCI' },
  { label: 'PAYX	Paychex, Inc.', id: 'PAYX' },
  { label: 'KHC	The Kraft Heinz Company', id: 'KHC' },
  { label: 'A	Agilent Technologies, Inc.', id: 'A' },
  { label: 'BK	The Bank of New York Mellon Cor', id: 'BK' },
  { label: 'CCI	Crown Castle Inc.', id: 'CCI' },
  { label: 'AMP	Ameriprise Financial, Inc.', id: 'AMP' },
  { label: 'PRU	Prudential Financial, Inc.', id: 'PRU' },
  { label: 'IQV	IQVIA Holdings, Inc.', id: 'IQV' },
  { label: 'KMI	Kinder Morgan, Inc.', id: 'KMI' },
  { label: 'IDXX	IDEXX Laboratories, Inc.', id: 'IDXX' },
  { label: 'NUE	Nucor Corporation', id: 'NUE' },
  { label: 'DOW	Dow Inc.', id: 'DOW' },
  { label: 'LHX	L3Harris Technologies, Inc.', id: 'LHX' },
  { label: 'FIS	Fidelity National Information S', id: 'FIS' },
  { label: 'CNC	Centene Corporation', id: 'CNC' },
  { label: 'HSY	The Hershey Company', id: 'HSY' },
  { label: 'CMI	Cummins Inc.', id: 'CMI' },
  { label: 'HUM	Humana Inc.', id: 'HUM' },
  { label: 'KR	Kroger Company (The)', id: 'KR' },
  { label: 'ODFL	Old Dominion Freight Line, Inc.', id: 'ODFL' },
  { label: 'CTVA	Corteva, Inc.', id: 'CTVA' },
  { label: 'GIS	General Mills, Inc.', id: 'GIS' },
  { label: 'PWR	Quanta Services, Inc.', id: 'PWR' },
  { label: 'CHTR	Charter Communications, Inc.', id: 'CHTR' },
  { label: 'AME	AMETEK, Inc.', id: 'AME' },
  { label: 'KVUE	Kenvue Inc.', id: 'KVUE' },
  { label: 'OTIS	Otis Worldwide Corporation', id: 'OTIS' },
  { label: 'FAST	Fastenal Company', id: 'FAST' },
  { label: 'YUM	Yum! Brands, Inc.', id: 'YUM' },
  { label: 'MSCI	MSCI Inc.', id: 'MSCI' },
  { label: 'GEHC	GE HealthCare Technologies Inc.', id: 'GEHC' },
  { label: 'SYY	Sysco Corporation', id: 'SYY' },
  { label: 'EXC	Exelon Corporation', id: 'EXC' },
  { label: 'MLM	Martin Marietta Materials, Inc.', id: 'MLM' },
  { label: 'ACGL	Arch Capital Group Ltd.', id: 'ACGL' },
  { label: 'PEG	Public Service Enterprise Group', id: 'PEG' },
  { label: 'IR	Ingersoll Rand Inc.', id: 'IR' },
  { label: 'CSGP	CoStar Group, Inc.', id: 'CSGP' },
  { label: 'RCL	Royal Caribbean Cruises Ltd.', id: 'RCL' },
  { label: 'FANG	Diamondback Energy, Inc.', id: 'FANG' },
  { label: 'VMC	Vulcan Materials Company (Holdi', id: 'VMC' },
  { label: 'VRSK	Verisk Analytics, Inc.', id: 'VRSK' },
  { label: 'NDAQ	Nasdaq, Inc.', id: 'NDAQ' },
  { label: 'LVS	Las Vegas Sands Corp.', id: 'LVS' },
  { label: 'XYL	Xylem Inc.', id: 'XYL' },
  { label: 'MPWR	Monolithic Power Systems, Inc.', id: 'MPWR' },
  { label: 'IT	Gartner, Inc.', id: 'IT' },
  { label: 'EA	Electronic Arts Inc.', id: 'EA' },
  { label: 'DAL	Delta Air Lines, Inc.', id: 'DAL' },
  { label: 'ED	Consolidated Edison, Inc.', id: 'ED' },
  { label: 'CTSH	Cognizant Technology Solutions ', id: 'CTSH' },
  { label: 'HWM	Howmet Aerospace Inc.', id: 'HWM' },
  { label: 'LYB	LyondellBasell Industries NV', id: 'LYB' },
  { label: 'DD	DuPont de Nemours, Inc.', id: 'DD' },
  { label: 'FICO	Fair Isaac Corproation', id: 'FICO' },
  { label: 'HAL	Halliburton Company', id: 'HAL' },
  { label: 'VST	Vistra Corp.', id: 'VST' },
  { label: 'BKR	Baker Hughes Company', id: 'BKR' },
  { label: 'GRMN	Garmin Ltd.', id: 'GRMN' },
  { label: 'EXR	Extra Space Storage Inc', id: 'EXR' },
  { label: 'MTD	Mettler-Toledo International, I', id: 'MTD' },
  { label: 'BIIB	Biogen Inc.', id: 'BIIB' },
  { label: 'PPG	PPG Industries, Inc.', id: 'PPG' },
  { label: 'DVN	Devon Energy Corporation', id: 'DVN' },
  { label: 'RMD	ResMed Inc.', id: 'RMD' },
  { label: 'ROK	Rockwell Automation, Inc.', id: 'ROK' },
  { label: 'ADM	Archer-Daniels-Midland Company', id: 'ADM' },
  { label: 'DG	Dollar General Corporation', id: 'DG' },
  { label: 'DFS	Discover Financial Services', id: 'DFS' },
  { label: 'XEL	Xcel Energy Inc.', id: 'XEL' },
  { label: 'VICI	VICI Properties Inc.', id: 'VICI' },
  { label: 'ON	ON Semiconductor Corporation', id: 'ON' },
  { label: 'HIG	Hartford Financial Services Gro', id: 'HIG' },
  { label: 'CDW	CDW Corporation', id: 'CDW' },
  { label: 'EFX	Equifax, Inc.', id: 'EFX' },
  { label: 'WAB	Westinghouse Air Brake Technolo', id: 'WAB' },
  { label: 'GLW	Corning Incorporated', id: 'GLW' },
  { label: 'TSCO	Tractor Supply Company', id: 'TSCO' },
  { label: 'HPQ	HP Inc.', id: 'HPQ' },
  { label: 'EIX	Edison International', id: 'EIX' },
  { label: 'ANSS	ANSYS, Inc.', id: 'ANSS' },
  { label: 'AVB	AvalonBay Communities, Inc.', id: 'AVB' },
  { label: 'GPN	Global Payments Inc.', id: 'GPN' },
  { label: 'CBRE	CBRE Group Inc', id: 'CBRE' },
  { label: 'FTV	Fortive Corporation', id: 'FTV' },
  { label: 'WEC	WEC Energy Group, Inc.', id: 'WEC' },
  { label: 'WST	West Pharmaceutical Services, I', id: 'WST' },
  { label: 'FITB	Fifth Third Bancorp', id: 'FITB' },
  { label: 'DLTR	Dollar Tree, Inc.', id: 'DLTR' },
  { label: 'AWK	American Water Works Company, I', id: 'AWK' },
  { label: 'WTW	Willis Towers Watson Public Lim', id: 'WTW' },
  { label: 'CHD	Church & Dwight Company, Inc.', id: 'CHD' },
  { label: 'KEYS	Keysight Technologies Inc.', id: 'KEYS' },
  { label: 'RJF	Raymond James Financial, Inc.', id: 'RJF' },
  { label: 'EBAY	eBay Inc.', id: 'EBAY' },
  { label: 'MTB	M&T Bank Corporation', id: 'MTB' },
  { label: 'DOV	Dover Corporation', id: 'DOV' },
  { label: 'EQR	Equity Residential', id: 'EQR' },
  { label: 'TRGP	Targa Resources, Inc.', id: 'TRGP' },
  { label: 'ZBH	Zimmer Biomet Holdings, Inc.', id: 'ZBH' },
  { label: 'TROW	T. Rowe Price Group, Inc.', id: 'TROW' },
  { label: 'TTWO	Take-Two Interactive Software, ', id: 'TTWO' },
  { label: 'BRO	Brown & Brown, Inc.', id: 'BRO' },
  { label: 'IFF	International Flavors & Fragran', id: 'IFF' },
  { label: 'PHM	PulteGroup, Inc.', id: 'PHM' },
  { label: 'CAH	Cardinal Health, Inc.', id: 'CAH' },
  { label: 'NVR	NVR, Inc.', id: 'NVR' },
  { label: 'ETR	Entergy Corporation', id: 'ETR' },
  { label: 'DTE	DTE Energy Company', id: 'DTE' },
  { label: 'VLTO	Veralto Corp', id: 'VLTO' },
  { label: 'IRM	Iron Mountain Incorporated (Del', id: 'IRM' },
  { label: 'WDC	Western Digital Corporation', id: 'WDC' },
  { label: 'BF-B	Brown Forman Inc', id: 'BF-B' },
  { label: 'BR	Broadridge Financial Solutions,', id: 'BR' },
  { label: 'STT	State Street Corporation', id: 'STT' },
  { label: 'FE	FirstEnergy Corp.', id: 'FE' },
  { label: 'AXON	Axon Enterprise, Inc.', id: 'AXON' },
  { label: 'STE	STERIS plc (Ireland)', id: 'STE' },
  { label: 'ROL	Rollins, Inc.', id: 'ROL' },
  { label: 'WY	Weyerhaeuser Company', id: 'WY' },
  { label: 'APTV	Aptiv PLC', id: 'APTV' },
  { label: 'LYV	Live Nation Entertainment, Inc.', id: 'LYV' },
  { label: 'NTAP	NetApp, Inc.', id: 'NTAP' },
  { label: 'HPE	Hewlett Packard Enterprise Comp', id: 'HPE' },
  { label: 'DECK	Deckers Outdoor Corporation', id: 'DECK' },
  { label: 'HUBB	Hubbell Inc', id: 'HUBB' },
  { label: 'ES	Eversource Energy (D/B/A)', id: 'ES' },
  { label: 'GPC	Genuine Parts Company', id: 'GPC' },
  { label: 'PTC	PTC Inc.', id: 'PTC' },
  { label: 'PPL	PPL Corporation', id: 'PPL' },
  { label: 'BALL	Ball Corporation', id: 'BALL' },
  { label: 'STLD	Steel Dynamics, Inc.', id: 'STLD' },
  { label: 'INVH	Invitation Homes Inc.', id: 'INVH' },
  { label: 'ARE	Alexandria Real Estate Equities', id: 'ARE' },
  { label: 'TSN	Tyson Foods, Inc.', id: 'TSN' },
  { label: 'SBAC	SBA Communications Corporation', id: 'SBAC' },
  { label: 'K	Kellanova', id: 'K' },
  { label: 'CTRA	Coterra Energy Inc.', id: 'CTRA' },
  { label: 'WAT	Waters Corporation', id: 'WAT' },
  { label: 'MOH	Molina Healthcare Inc', id: 'MOH' },
  { label: 'TYL	Tyler Technologies, Inc.', id: 'TYL' },
  { label: 'ALGN	Align Technology, Inc.', id: 'ALGN' },
  { label: 'FSLR	First Solar, Inc.', id: 'FSLR' },
  { label: 'MKC	McCormick & Company, Incorporat', id: 'MKC' },
  { label: 'WRB	W.R. Berkley Corporation', id: 'WRB' },
  { label: 'BLDR	Builders FirstSource, Inc.', id: 'BLDR' },
  { label: 'HBAN	Huntington Bancshares Incorpora', id: 'HBAN' },
  { label: 'WBD	Warner Bros. Discovery, Inc. - ', id: 'WBD' },
  { label: 'LDOS	Leidos Holdings, Inc.', id: 'LDOS' },
  { label: 'CPAY	Corpay, Inc.', id: 'CPAY' },
  { label: 'AEE	Ameren Corporation', id: 'AEE' },
  { label: 'STX	Seagate Technology Holdings PLC', id: 'STX' },
  { label: 'PFG	Principal Financial Group Inc', id: 'PFG' },
  { label: 'HRL	Hormel Foods Corporation', id: 'HRL' },
  { label: 'ULTA	Ulta Beauty, Inc.', id: 'ULTA' },
  { label: 'VTR	Ventas, Inc.', id: 'VTR' },
  { label: 'TER	Teradyne, Inc.', id: 'TER' },
  { label: 'CBOE	Cboe Global Markets, Inc.', id: 'CBOE' },
  { label: 'CNP	CenterPoint Energy, Inc (Holdin', id: 'CNP' },
  { label: 'CCL	Carnival Corporation', id: 'CCL' },
  { label: 'COO	The Cooper Companies, Inc.', id: 'COO' },
  { label: 'CMS	CMS Energy Corporation', id: 'CMS' },
  { label: 'OMC	Omnicom Group Inc.', id: 'OMC' },
  { label: 'TDY	Teledyne Technologies Incorpora', id: 'TDY' },
  { label: 'CINF	Cincinnati Financial Corporatio', id: 'CINF' },
  { label: 'SYF	Synchrony Financial', id: 'SYF' },
  { label: 'BAX	Baxter International Inc.', id: 'BAX' },
  { label: 'AVY	Avery Dennison Corporation', id: 'AVY' },
  { label: 'RF	Regions Financial Corporation', id: 'RF' },
  { label: "DPZ	Domino's Pizza Inc", id: 'DPZ' },
  { label: 'CLX	Clorox Company (The)', id: 'CLX' },
  { label: 'NTRS	Northern Trust Corporation', id: 'NTRS' },
  { label: 'DRI	Darden Restaurants, Inc.', id: 'DRI' },
  { label: 'ATO	Atmos Energy Corporation', id: 'ATO' },
  { label: 'ILMN	Illumina, Inc.', id: 'ILMN' },
  { label: 'JBHT	J.B. Hunt Transport Services, I', id: 'JBHT' },
  { label: 'HOLX	Hologic, Inc.', id: 'HOLX' },
  { label: 'LH	Laboratory Corporation of Ameri', id: 'LH' },
  { label: 'CE	Celanese Corporation', id: 'CE' },
  { label: 'NRG	NRG Energy, Inc.', id: 'NRG' },
  { label: 'J	Jacobs Solutions Inc.', id: 'J' },
  { label: 'UAL	United Airlines Holdings, Inc.', id: 'UAL' },
  { label: 'L	Loews Corporation', id: 'L' },
  { label: 'ESS	Essex Property Trust, Inc.', id: 'ESS' },
  { label: 'EQT	EQT Corporation', id: 'EQT' },
  { label: 'IEX	IDEX Corporation', id: 'IEX' },
  { label: 'VRSN	VeriSign, Inc.', id: 'VRSN' },
  { label: 'TXT	Textron Inc.', id: 'TXT' },
  { label: 'FDS	FactSet Research Systems Inc.', id: 'FDS' },
  { label: 'EXPD	Expeditors International of Was', id: 'EXPD' },
  { label: 'EG	Everest Group, Ltd.', id: 'EG' },
  { label: 'CFG	Citizens Financial Group, Inc.', id: 'CFG' },
  { label: 'LUV	Southwest Airlines Company', id: 'LUV' },
  { label: 'MAA	Mid-America Apartment Communiti', id: 'MAA' },
  { label: 'ZBRA	Zebra Technologies Corporation', id: 'ZBRA' },
  { label: 'PKG	Packaging Corporation of Americ', id: 'PKG' },
  { label: 'BBY	Best Buy Co., Inc.', id: 'BBY' },
  { label: 'NDSN	Nordson Corporation', id: 'NDSN' },
  { label: 'MAS	Masco Corporation', id: 'MAS' },
  { label: 'DGX	Quest Diagnostics Incorporated', id: 'DGX' },
  { label: 'ALB	Albemarle Corporation', id: 'ALB' },
  { label: 'FOX	Fox Corporation', id: 'FOX' },
  { label: 'BG	Bunge Limited', id: 'BG' },
  { label: 'MRO	Marathon Oil Corporation', id: 'MRO' },
  { label: 'FOXA	Fox Corporation', id: 'FOXA' },
  { label: 'AMCR	Amcor plc', id: 'AMCR' },
  { label: 'EXPE	Expedia Group, Inc.', id: 'EXPE' },
  { label: 'GEN	Gen Digital Inc.', id: 'GEN' },
  { label: 'CAG	ConAgra Brands, Inc.', id: 'CAG' },
  { label: 'WBA	Walgreens Boots Alliance, Inc.', id: 'WBA' },
  { label: 'SNA	Snap-On Incorporated', id: 'SNA' },
  { label: 'SWKS	Skyworks Solutions, Inc.', id: 'SWKS' },
  { label: 'ENPH	Enphase Energy, Inc.', id: 'ENPH' },
  { label: 'UDR	UDR, Inc.', id: 'UDR' },
  { label: 'NWSA	News Corporation', id: 'NWSA' },
  { label: 'NWS	News Corporation', id: 'NWS' },
  { label: 'POOL	Pool Corporation', id: 'POOL' },
  { label: 'JBL	Jabil Inc.', id: 'JBL' },
  { label: 'KEY	KeyCorp', id: 'KEY' },
  { label: 'AES	The AES Corporation', id: 'AES' },
  { label: 'AKAM	Akamai Technologies, Inc.', id: 'AKAM' },
  { label: 'TRMB	Trimble Inc.', id: 'TRMB' },
  { label: 'PNR	Pentair plc.', id: 'PNR' },
  { label: 'SWK	Stanley Black & Decker, Inc.', id: 'SWK' },
  { label: 'DOC	Healthpeak Properties, Inc.', id: 'DOC' },
  { label: 'CPB	Campbell Soup Company', id: 'CPB' },
  { label: 'CF	CF Industries Holdings, Inc.', id: 'CF' },
  { label: 'IP	International Paper Company', id: 'IP' },
  { label: 'WRK	Westrock Company', id: 'WRK' },
  { label: 'VTRS	Viatris Inc.', id: 'VTRS' },
  { label: 'LNT	Alliant Energy Corporation', id: 'LNT' },
  { label: 'HST	Host Hotels & Resorts, Inc.', id: 'HST' },
  { label: 'RVTY	Revvity, Inc.', id: 'RVTY' },
  { label: 'NI	NiSource Inc', id: 'NI' },
  { label: 'KIM	Kimco Realty Corporation (HC)', id: 'KIM' },
  { label: 'TECH	Bio-Techne Corp', id: 'TECH' },
  { label: 'EVRG	Evergy, Inc.', id: 'EVRG' },
  { label: 'MGM	MGM Resorts International', id: 'MGM' },
  { label: 'AOS	A.O. Smith Corporation', id: 'AOS' },
  { label: 'TAP	Molson Coors Beverage Company', id: 'TAP' },
  { label: 'BEN	Franklin Resources, Inc.', id: 'BEN' },
  { label: 'JKHY	Jack Henry & Associates, Inc.', id: 'JKHY' },
  { label: 'LW	Lamb Weston Holdings, Inc.', id: 'LW' },
  { label: 'SJM	The J.M. Smucker Company', id: 'SJM' },
  { label: 'DVA	DaVita Inc.', id: 'DVA' },
  { label: 'UHS	Universal Health Services, Inc.', id: 'UHS' },
  { label: 'INCY	Incyte Corporation', id: 'INCY' },
  { label: 'EMN	Eastman Chemical Company', id: 'EMN' },
  { label: 'LKQ	LKQ Corporation', id: 'LKQ' },
  { label: 'IPG	Interpublic Group of Companies,', id: 'IPG' },
  { label: 'CRL	Charles River Laboratories Inte', id: 'CRL' },
  { label: 'PODD	Insulet Corporation', id: 'PODD' },
  { label: 'CPT	Camden Property Trust', id: 'CPT' },
  { label: 'KMX	CarMax Inc', id: 'KMX' },
  { label: 'APA	APA Corporation', id: 'APA' },
  { label: 'JNPR	Juniper Networks, Inc.', id: 'JNPR' },
  { label: 'REG	Regency Centers Corporation', id: 'REG' },
  { label: 'ALLE	Allegion plc', id: 'ALLE' },
  { label: 'SOLV	Solventum Corporation', id: 'SOLV' },
  { label: 'WYNN	Wynn Resorts, Limited', id: 'WYNN' },
  { label: 'BBWI	Bath & Body Works, Inc.', id: 'BBWI' },
  { label: 'RL	Ralph Lauren Corporation', id: 'RL' },
  { label: 'EPAM	EPAM Systems, Inc.', id: 'EPAM' },
  { label: 'CTLT	Catalent, Inc.', id: 'CTLT' },
  { label: 'PAYC	Paycom Software, Inc.', id: 'PAYC' },
  { label: 'FFIV	F5, Inc.', id: 'FFIV' },
  { label: 'HII	Huntington Ingalls Industries, ', id: 'HII' },
  { label: 'CHRW	C.H. Robinson Worldwide, Inc.', id: 'CHRW' },
  { label: 'BXP	Boston Properties, Inc.', id: 'BXP' },
  { label: 'TFX	Teleflex Incorporated', id: 'TFX' },
  { label: 'DAY	Dayforce, Inc.', id: 'DAY' },
  { label: 'MOS	Mosaic Company (The)', id: 'MOS' },
  { label: 'AAL	American Airlines Group, Inc.', id: 'AAL' },
  { label: 'QRVO	Qorvo, Inc.', id: 'QRVO' },
  { label: 'HSIC	Henry Schein, Inc.', id: 'HSIC' },
  { label: 'TPR	Tapestry, Inc.', id: 'TPR' },
  { label: 'AIZ	Assurant, Inc.', id: 'AIZ' },
  { label: 'PARA	Paramount Global', id: 'PARA' },
  { label: 'PNW	Pinnacle West Capital Corporati', id: 'PNW' },
  { label: 'BWA	BorgWarner Inc.', id: 'BWA' },
  { label: 'FRT	Federal Realty Investment Trust', id: 'FRT' },
  { label: 'FMC	FMC Corporation', id: 'FMC' },
  { label: 'HAS	Hasbro, Inc.', id: 'HAS' },
  { label: 'GNRC	Generac Holdlings Inc.', id: 'GNRC' },
  { label: 'MTCH	Match Group, Inc.', id: 'MTCH' },
  { label: 'GL	Globe Life Inc.', id: 'GL' },
  { label: 'BIO	Bio-Rad Laboratories, Inc.', id: 'BIO' },
  { label: 'CZR	Caesars Entertainment, Inc.', id: 'CZR' },
  { label: 'MKTX	MarketAxess Holdings, Inc.', id: 'MKTX' },
  { label: 'MHK	Mohawk Industries, Inc.', id: 'MHK' },
  { label: 'RHI	Robert Half Inc.', id: 'RHI' },
  { label: 'ETSY	Etsy, Inc.', id: 'ETSY' },
  { label: 'CMA	Comerica Incorporated', id: 'CMA' },
  { label: 'IVZ	Invesco Ltd', id: 'IVZ' },
  { label: 'NCLH	Norwegian Cruise Line Holdings ', id: 'NCLH' },
];
