export default [
  {
    id: '0000320193:2023:FY',
    start_date: '2022-09-25',
    end_date: '2023-09-30',
    filing_date: '2023-11-03',
    acceptance_datetime: '2023-11-02T22:08:27Z',
    timeframe: 'annual',
    fiscal_period: 'FY',
    fiscal_year: '2023',
    cik: '0000320193',
    sic: '3571',
    tickers: ['AAPL'],
    company_name: 'Apple Inc.',
    source_filing_url:
      'https://api.polygon.io/v1/reference/sec/filings/0000320193-23-000106',
    source_filing_file_url:
      'http://api.polygon.io/v1/reference/sec/filings/0000320193-23-000106/files/aapl-20230930_htm.xml',
    financials: {
      comprehensive_income: {
        other_comprehensive_income_loss: {
          value: 9.6652e10,
          unit: 'USD',
          label: 'Other Comprehensive Income/Loss',
          order: 400,
        },
        comprehensive_income_loss: {
          value: 9.6652e10,
          unit: 'USD',
          label: 'Comprehensive Income/Loss',
          order: 100,
        },
        other_comprehensive_income_loss_attributable_to_parent: {
          value: -3.43e8,
          unit: 'USD',
          label: 'Other Comprehensive Income/Loss Attributable To Parent',
          order: 600,
        },
        comprehensive_income_loss_attributable_to_parent: {
          value: 9.6652e10,
          unit: 'USD',
          label: 'Comprehensive Income/Loss Attributable To Parent',
          order: 300,
        },
        comprehensive_income_loss_attributable_to_noncontrolling_interest: {
          value: 0,
          unit: 'USD',
          label:
            'Comprehensive Income/Loss Attributable To Noncontrolling Interest',
          order: 200,
        },
      },
      balance_sheet: {
        equity_attributable_to_parent: {
          value: 6.2146e10,
          unit: 'USD',
          label: 'Equity Attributable To Parent',
          order: 1600,
        },
        assets: {
          value: 3.52583e11,
          unit: 'USD',
          label: 'Assets',
          order: 100,
        },
        other_noncurrent_assets: {
          value: 1.65302e11,
          unit: 'USD',
          label: 'Other Non-current Assets',
          order: 350,
        },
        noncurrent_liabilities: {
          value: 1.45129e11,
          unit: 'USD',
          label: 'Noncurrent Liabilities',
          order: 800,
        },
        accounts_payable: {
          value: 6.2611e10,
          unit: 'USD',
          label: 'Accounts Payable',
          order: 710,
        },
        current_assets: {
          value: 1.43566e11,
          unit: 'USD',
          label: 'Current Assets',
          order: 200,
        },
        long_term_debt: {
          value: 1.05103e11,
          unit: 'USD',
          label: 'Long-term Debt',
          order: 810,
        },
        other_current_assets: {
          value: 1.37235e11,
          unit: 'USD',
          label: 'Other Current Assets',
          order: 250,
        },
        liabilities: {
          value: 2.90437e11,
          unit: 'USD',
          label: 'Liabilities',
          order: 600,
        },
        fixed_assets: {
          value: 4.3715e10,
          unit: 'USD',
          label: 'Fixed Assets',
          order: 320,
        },
        equity: {
          value: 6.2146e10,
          unit: 'USD',
          label: 'Equity',
          order: 1400,
        },
        liabilities_and_equity: {
          value: 3.52583e11,
          unit: 'USD',
          label: 'Liabilities And Equity',
          order: 1900,
        },
        inventory: {
          value: 6.331e9,
          unit: 'USD',
          label: 'Inventory',
          order: 230,
        },
        other_noncurrent_liabilities: {
          value: 4.0026e10,
          unit: 'USD',
          label: 'Other Non-current Liabilities',
          order: 820,
        },
        current_liabilities: {
          value: 1.45308e11,
          unit: 'USD',
          label: 'Current Liabilities',
          order: 700,
        },
        other_current_liabilities: {
          value: 8.2697e10,
          unit: 'USD',
          label: 'Other Current Liabilities',
          order: 740,
        },
        equity_attributable_to_noncontrolling_interest: {
          value: 0,
          unit: 'USD',
          label: 'Equity Attributable To Noncontrolling Interest',
          order: 1500,
        },
        noncurrent_assets: {
          value: 2.09017e11,
          unit: 'USD',
          label: 'Noncurrent Assets',
          order: 300,
        },
      },
      cash_flow_statement: {
        net_cash_flow: {
          value: 5.76e9,
          unit: 'USD',
          label: 'Net Cash Flow',
          order: 1100,
        },
        net_cash_flow_from_financing_activities: {
          value: -1.08488e11,
          unit: 'USD',
          label: 'Net Cash Flow From Financing Activities',
          order: 700,
        },
        net_cash_flow_from_investing_activities_continuing: {
          value: 3.705e9,
          unit: 'USD',
          label: 'Net Cash Flow From Investing Activities, Continuing',
          order: 500,
        },
        net_cash_flow_from_operating_activities: {
          value: 1.10543e11,
          unit: 'USD',
          label: 'Net Cash Flow From Operating Activities',
          order: 100,
        },
        net_cash_flow_from_investing_activities: {
          value: 3.705e9,
          unit: 'USD',
          label: 'Net Cash Flow From Investing Activities',
          order: 400,
        },
        net_cash_flow_from_financing_activities_continuing: {
          value: -1.08488e11,
          unit: 'USD',
          label: 'Net Cash Flow From Financing Activities, Continuing',
          order: 800,
        },
        net_cash_flow_from_operating_activities_continuing: {
          value: 1.10543e11,
          unit: 'USD',
          label: 'Net Cash Flow From Operating Activities, Continuing',
          order: 200,
        },
        net_cash_flow_continuing: {
          value: 5.76e9,
          unit: 'USD',
          label: 'Net Cash Flow, Continuing',
          order: 1200,
        },
      },
      income_statement: {
        costs_and_expenses: {
          value: 2.69549e11,
          unit: 'USD',
          label: 'Costs And Expenses',
          order: 600,
        },
        nonoperating_income_loss: {
          value: -5.65e8,
          unit: 'USD',
          label: 'Nonoperating Income/Loss',
          order: 900,
        },
        operating_income_loss: {
          value: 1.14301e11,
          unit: 'USD',
          label: 'Operating Income/Loss',
          order: 1100,
        },
        diluted_earnings_per_share: {
          value: 6.13,
          unit: 'USD / shares',
          label: 'Diluted Earnings Per Share',
          order: 4300,
        },
        selling_general_and_administrative_expenses: {
          value: 2.4932e10,
          unit: 'USD',
          label: 'Selling, General, and Administrative Expenses',
          order: 1010,
        },
        net_income_loss: {
          value: 9.6995e10,
          unit: 'USD',
          label: 'Net Income/Loss',
          order: 3200,
        },
        net_income_loss_attributable_to_parent: {
          value: 9.6995e10,
          unit: 'USD',
          label: 'Net Income/Loss Attributable To Parent',
          order: 3500,
        },
        basic_average_shares: {
          value: 1.5744231e10,
          unit: 'shares',
          label: 'Basic Average Shares',
          order: 4400,
        },
        benefits_costs_expenses: {
          value: 2.69549e11,
          unit: 'USD',
          label: 'Benefits Costs and Expenses',
          order: 200,
        },
        gross_profit: {
          value: 1.69148e11,
          unit: 'USD',
          label: 'Gross Profit',
          order: 800,
        },
        interest_expense_operating: {
          value: 3.933e9,
          unit: 'USD',
          label: 'Interest Expense, Operating',
          order: 2700,
        },
        revenues: {
          value: 3.83285e11,
          unit: 'USD',
          label: 'Revenues',
          order: 100,
        },
        preferred_stock_dividends_and_other_adjustments: {
          value: 0,
          unit: 'USD',
          label: 'Preferred Stock Dividends And Other Adjustments',
          order: 3900,
        },
        research_and_development: {
          value: 2.9915e10,
          unit: 'USD',
          label: 'Research and Development',
          order: 1030,
        },
        cost_of_revenue: {
          value: 2.14137e11,
          unit: 'USD',
          label: 'Cost Of Revenue',
          order: 300,
        },
        participating_securities_distributed_and_undistributed_earnings_loss_basic:
          {
            value: 0,
            unit: 'USD',
            label:
              'Participating Securities, Distributed And Undistributed Earnings/Loss, Basic',
            order: 3800,
          },
        diluted_average_shares: {
          value: 1.5812547e10,
          unit: 'shares',
          label: 'Diluted Average Shares',
          order: 4500,
        },
        income_tax_expense_benefit: {
          value: 1.6741e10,
          unit: 'USD',
          label: 'Income Tax Expense/Benefit',
          order: 2200,
        },
        operating_expenses: {
          value: 5.4847e10,
          unit: 'USD',
          label: 'Operating Expenses',
          order: 1000,
        },
        net_income_loss_attributable_to_noncontrolling_interest: {
          value: 0,
          unit: 'USD',
          label: 'Net Income/Loss Attributable To Noncontrolling Interest',
          order: 3300,
        },
        net_income_loss_available_to_common_stockholders_basic: {
          value: 9.6995e10,
          unit: 'USD',
          label: 'Net Income/Loss Available To Common Stockholders, Basic',
          order: 3700,
        },
        income_loss_from_continuing_operations_before_tax: {
          value: 1.13736e11,
          unit: 'USD',
          label: 'Income/Loss From Continuing Operations Before Tax',
          order: 1500,
        },
        basic_earnings_per_share: {
          value: 6.16,
          unit: 'USD / shares',
          label: 'Basic Earnings Per Share',
          order: 4200,
        },
        income_loss_from_continuing_operations_after_tax: {
          value: 9.6995e10,
          unit: 'USD',
          label: 'Income/Loss From Continuing Operations After Tax',
          order: 1400,
        },
      },
    },
  },
  {
    id: '0000320193:2022:FY',
    start_date: '2021-09-26',
    end_date: '2022-09-24',
    filing_date: '2022-10-28',
    timeframe: 'annual',
    fiscal_period: 'FY',
    fiscal_year: '2022',
    cik: '0000320193',
    sic: '3571',
    tickers: ['AAPL'],
    company_name: 'Apple Inc.',
    source_filing_url:
      'https://api.polygon.io/v1/reference/sec/filings/0000320193-22-000108',
    source_filing_file_url:
      'https://api.polygon.io/v1/reference/sec/filings/0000320193-22-000108/files/aapl-20220924_htm.xml',
    financials: {
      income_statement: {
        income_loss_from_continuing_operations_after_tax: {
          value: 9.9803e10,
          unit: 'USD',
          label: 'Income/Loss From Continuing Operations After Tax',
          order: 1400,
        },
        net_income_loss_attributable_to_noncontrolling_interest: {
          value: 0,
          unit: 'USD',
          label: 'Net Income/Loss Attributable To Noncontrolling Interest',
          order: 3300,
        },
        diluted_average_shares: {
          value: 1.6325819e10,
          unit: 'shares',
          label: 'Diluted Average Shares',
          order: 4500,
        },
        income_loss_from_continuing_operations_before_tax: {
          value: 1.19103e11,
          unit: 'USD',
          label: 'Income/Loss From Continuing Operations Before Tax',
          order: 1500,
        },
        operating_income_loss: {
          value: 1.19437e11,
          unit: 'USD',
          label: 'Operating Income/Loss',
          order: 1100,
        },
        gross_profit: {
          value: 1.70782e11,
          unit: 'USD',
          label: 'Gross Profit',
          order: 800,
        },
        cost_of_revenue: {
          value: 2.23546e11,
          unit: 'USD',
          label: 'Cost Of Revenue',
          order: 300,
        },
        diluted_earnings_per_share: {
          value: 6.11,
          unit: 'USD / shares',
          label: 'Diluted Earnings Per Share',
          order: 4300,
        },
        research_and_development: {
          value: 2.6251e10,
          unit: 'USD',
          label: 'Research and Development',
          order: 1030,
        },
        basic_earnings_per_share: {
          value: 6.15,
          unit: 'USD / shares',
          label: 'Basic Earnings Per Share',
          order: 4200,
        },
        preferred_stock_dividends_and_other_adjustments: {
          value: 0,
          unit: 'USD',
          label: 'Preferred Stock Dividends And Other Adjustments',
          order: 3900,
        },
        revenues: {
          value: 3.94328e11,
          unit: 'USD',
          label: 'Revenues',
          order: 100,
        },
        benefits_costs_expenses: {
          value: 2.75225e11,
          unit: 'USD',
          label: 'Benefits Costs and Expenses',
          order: 200,
        },
        net_income_loss_attributable_to_parent: {
          value: 9.9803e10,
          unit: 'USD',
          label: 'Net Income/Loss Attributable To Parent',
          order: 3500,
        },
        income_tax_expense_benefit_deferred: {
          value: 8.95e8,
          unit: 'USD',
          label: 'Income Tax Expense/Benefit, Deferred',
          order: 2400,
        },
        operating_expenses: {
          value: 5.1345e10,
          unit: 'USD',
          label: 'Operating Expenses',
          order: 1000,
        },
        net_income_loss_available_to_common_stockholders_basic: {
          value: 9.9803e10,
          unit: 'USD',
          label: 'Net Income/Loss Available To Common Stockholders, Basic',
          order: 3700,
        },
        net_income_loss: {
          value: 9.9803e10,
          unit: 'USD',
          label: 'Net Income/Loss',
          order: 3200,
        },
        participating_securities_distributed_and_undistributed_earnings_loss_basic:
          {
            value: 0,
            unit: 'USD',
            label:
              'Participating Securities, Distributed And Undistributed Earnings/Loss, Basic',
            order: 3800,
          },
        nonoperating_income_loss: {
          value: -3.34e8,
          unit: 'USD',
          label: 'Nonoperating Income/Loss',
          order: 900,
        },
        interest_expense_operating: {
          value: 2.931e9,
          unit: 'USD',
          label: 'Interest Expense, Operating',
          order: 2700,
        },
        income_tax_expense_benefit: {
          value: 1.93e10,
          unit: 'USD',
          label: 'Income Tax Expense/Benefit',
          order: 2200,
        },
        costs_and_expenses: {
          value: 2.75225e11,
          unit: 'USD',
          label: 'Costs And Expenses',
          order: 600,
        },
        selling_general_and_administrative_expenses: {
          value: 2.5094e10,
          unit: 'USD',
          label: 'Selling, General, and Administrative Expenses',
          order: 1010,
        },
        basic_average_shares: {
          value: 1.6215963e10,
          unit: 'shares',
          label: 'Basic Average Shares',
          order: 4400,
        },
      },
      balance_sheet: {
        current_liabilities: {
          value: 1.53982e11,
          unit: 'USD',
          label: 'Current Liabilities',
          order: 700,
        },
        equity_attributable_to_noncontrolling_interest: {
          value: 0,
          unit: 'USD',
          label: 'Equity Attributable To Noncontrolling Interest',
          order: 1500,
        },
        accounts_payable: {
          value: 6.4115e10,
          unit: 'USD',
          label: 'Accounts Payable',
          order: 710,
        },
        equity_attributable_to_parent: {
          value: 5.0672e10,
          unit: 'USD',
          label: 'Equity Attributable To Parent',
          order: 1600,
        },
        fixed_assets: {
          value: 4.2117e10,
          unit: 'USD',
          label: 'Fixed Assets',
          order: 320,
        },
        other_noncurrent_assets: {
          value: 1.75233e11,
          unit: 'USD',
          label: 'Other Non-current Assets',
          order: 350,
        },
        other_current_liabilities: {
          value: 8.9867e10,
          unit: 'USD',
          label: 'Other Current Liabilities',
          order: 740,
        },
        inventory: {
          value: 4.946e9,
          unit: 'USD',
          label: 'Inventory',
          order: 230,
        },
        equity: {
          value: 5.0672e10,
          unit: 'USD',
          label: 'Equity',
          order: 1400,
        },
        liabilities: {
          value: 3.02083e11,
          unit: 'USD',
          label: 'Liabilities',
          order: 600,
        },
        noncurrent_assets: {
          value: 2.1735e11,
          unit: 'USD',
          label: 'Noncurrent Assets',
          order: 300,
        },
        other_current_assets: {
          value: 1.30459e11,
          unit: 'USD',
          label: 'Other Current Assets',
          order: 250,
        },
        assets: {
          value: 3.52755e11,
          unit: 'USD',
          label: 'Assets',
          order: 100,
        },
        liabilities_and_equity: {
          value: 3.52755e11,
          unit: 'USD',
          label: 'Liabilities And Equity',
          order: 1900,
        },
        current_assets: {
          value: 1.35405e11,
          unit: 'USD',
          label: 'Current Assets',
          order: 200,
        },
        noncurrent_liabilities: {
          value: 1.48101e11,
          unit: 'USD',
          label: 'Noncurrent Liabilities',
          order: 800,
        },
      },
      cash_flow_statement: {
        net_cash_flow_continuing: {
          value: -1.0952e10,
          unit: 'USD',
          label: 'Net Cash Flow, Continuing',
          order: 1200,
        },
        net_cash_flow_from_investing_activities_continuing: {
          value: -2.2354e10,
          unit: 'USD',
          label: 'Net Cash Flow From Investing Activities, Continuing',
          order: 500,
        },
        net_cash_flow_from_financing_activities_continuing: {
          value: -1.10749e11,
          unit: 'USD',
          label: 'Net Cash Flow From Financing Activities, Continuing',
          order: 800,
        },
        net_cash_flow_from_investing_activities: {
          value: -2.2354e10,
          unit: 'USD',
          label: 'Net Cash Flow From Investing Activities',
          order: 400,
        },
        net_cash_flow_from_operating_activities: {
          value: 1.22151e11,
          unit: 'USD',
          label: 'Net Cash Flow From Operating Activities',
          order: 100,
        },
        net_cash_flow_from_operating_activities_continuing: {
          value: 1.22151e11,
          unit: 'USD',
          label: 'Net Cash Flow From Operating Activities, Continuing',
          order: 200,
        },
        net_cash_flow_from_financing_activities: {
          value: -1.10749e11,
          unit: 'USD',
          label: 'Net Cash Flow From Financing Activities',
          order: 700,
        },
        net_cash_flow: {
          value: -1.0952e10,
          unit: 'USD',
          label: 'Net Cash Flow',
          order: 1100,
        },
      },
      comprehensive_income: {
        other_comprehensive_income_loss_attributable_to_parent: {
          value: -1.1272e10,
          unit: 'USD',
          label: 'Other Comprehensive Income/Loss Attributable To Parent',
          order: 600,
        },
        comprehensive_income_loss_attributable_to_parent: {
          value: 8.8531e10,
          unit: 'USD',
          label: 'Comprehensive Income/Loss Attributable To Parent',
          order: 300,
        },
        comprehensive_income_loss_attributable_to_noncontrolling_interest: {
          value: 0,
          unit: 'USD',
          label:
            'Comprehensive Income/Loss Attributable To Noncontrolling Interest',
          order: 200,
        },
        other_comprehensive_income_loss: {
          value: 8.8531e10,
          unit: 'USD',
          label: 'Other Comprehensive Income/Loss',
          order: 400,
        },
        comprehensive_income_loss: {
          value: 8.8531e10,
          unit: 'USD',
          label: 'Comprehensive Income/Loss',
          order: 100,
        },
      },
    },
  },
  {
    id: '0000320193:2021:FY',
    start_date: '2020-09-27',
    end_date: '2021-09-25',
    filing_date: '2021-10-29',
    timeframe: 'annual',
    fiscal_period: 'FY',
    fiscal_year: '2021',
    cik: '0000320193',
    sic: '3571',
    tickers: ['AAPL'],
    company_name: 'Apple Inc.',
    source_filing_url:
      'https://api.polygon.io/v1/reference/sec/filings/0000320193-21-000105',
    source_filing_file_url:
      'https://api.polygon.io/v1/reference/sec/filings/0000320193-21-000105/files/aapl-20210925_htm.xml',
    financials: {
      comprehensive_income: {
        other_comprehensive_income_loss: {
          value: 9.5249e10,
          unit: 'USD',
          label: 'Other Comprehensive Income/Loss',
          order: 400,
        },
        comprehensive_income_loss_attributable_to_noncontrolling_interest: {
          value: 0,
          unit: 'USD',
          label:
            'Comprehensive Income/Loss Attributable To Noncontrolling Interest',
          order: 200,
        },
        other_comprehensive_income_loss_attributable_to_parent: {
          value: 5.69e8,
          unit: 'USD',
          label: 'Other Comprehensive Income/Loss Attributable To Parent',
          order: 600,
        },
        comprehensive_income_loss: {
          value: 9.5249e10,
          unit: 'USD',
          label: 'Comprehensive Income/Loss',
          order: 100,
        },
        comprehensive_income_loss_attributable_to_parent: {
          value: 9.5249e10,
          unit: 'USD',
          label: 'Comprehensive Income/Loss Attributable To Parent',
          order: 300,
        },
      },
      income_statement: {
        net_income_loss_attributable_to_noncontrolling_interest: {
          value: 0,
          unit: 'USD',
          label: 'Net Income/Loss Attributable To Noncontrolling Interest',
          order: 3300,
        },
        selling_general_and_administrative_expenses: {
          value: 2.1973e10,
          unit: 'USD',
          label: 'Selling, General, and Administrative Expenses',
          order: 1010,
        },
        basic_earnings_per_share: {
          value: 5.67,
          unit: 'USD / shares',
          label: 'Basic Earnings Per Share',
          order: 4200,
        },
        basic_average_shares: {
          value: 1.6701272e10,
          unit: 'shares',
          label: 'Basic Average Shares',
          order: 4400,
        },
        interest_expense_operating: {
          value: 2.645e9,
          unit: 'USD',
          label: 'Interest Expense, Operating',
          order: 2700,
        },
        cost_of_revenue: {
          value: 2.12981e11,
          unit: 'USD',
          label: 'Cost Of Revenue',
          order: 300,
        },
        operating_income_loss: {
          value: 1.08949e11,
          unit: 'USD',
          label: 'Operating Income/Loss',
          order: 1100,
        },
        benefits_costs_expenses: {
          value: 2.5661e11,
          unit: 'USD',
          label: 'Benefits Costs and Expenses',
          order: 200,
        },
        net_income_loss_available_to_common_stockholders_basic: {
          value: 9.468e10,
          unit: 'USD',
          label: 'Net Income/Loss Available To Common Stockholders, Basic',
          order: 3700,
        },
        participating_securities_distributed_and_undistributed_earnings_loss_basic:
          {
            value: 0,
            unit: 'USD',
            label:
              'Participating Securities, Distributed And Undistributed Earnings/Loss, Basic',
            order: 3800,
          },
        operating_expenses: {
          value: 4.3887e10,
          unit: 'USD',
          label: 'Operating Expenses',
          order: 1000,
        },
        income_tax_expense_benefit_deferred: {
          value: -4.774e9,
          unit: 'USD',
          label: 'Income Tax Expense/Benefit, Deferred',
          order: 2400,
        },
        income_loss_from_continuing_operations_before_tax: {
          value: 1.09207e11,
          unit: 'USD',
          label: 'Income/Loss From Continuing Operations Before Tax',
          order: 1500,
        },
        income_tax_expense_benefit: {
          value: 1.4527e10,
          unit: 'USD',
          label: 'Income Tax Expense/Benefit',
          order: 2200,
        },
        costs_and_expenses: {
          value: 2.5661e11,
          unit: 'USD',
          label: 'Costs And Expenses',
          order: 600,
        },
        research_and_development: {
          value: 2.1914e10,
          unit: 'USD',
          label: 'Research and Development',
          order: 1030,
        },
        diluted_average_shares: {
          value: 1.6864919e10,
          unit: 'shares',
          label: 'Diluted Average Shares',
          order: 4500,
        },
        diluted_earnings_per_share: {
          value: 5.61,
          unit: 'USD / shares',
          label: 'Diluted Earnings Per Share',
          order: 4300,
        },
        net_income_loss: {
          value: 9.468e10,
          unit: 'USD',
          label: 'Net Income/Loss',
          order: 3200,
        },
        income_loss_from_continuing_operations_after_tax: {
          value: 9.468e10,
          unit: 'USD',
          label: 'Income/Loss From Continuing Operations After Tax',
          order: 1400,
        },
        revenues: {
          value: 3.65817e11,
          unit: 'USD',
          label: 'Revenues',
          order: 100,
        },
        preferred_stock_dividends_and_other_adjustments: {
          value: 0,
          unit: 'USD',
          label: 'Preferred Stock Dividends And Other Adjustments',
          order: 3900,
        },
        gross_profit: {
          value: 1.52836e11,
          unit: 'USD',
          label: 'Gross Profit',
          order: 800,
        },
        net_income_loss_attributable_to_parent: {
          value: 9.468e10,
          unit: 'USD',
          label: 'Net Income/Loss Attributable To Parent',
          order: 3500,
        },
        nonoperating_income_loss: {
          value: 2.58e8,
          unit: 'USD',
          label: 'Nonoperating Income/Loss',
          order: 900,
        },
      },
      cash_flow_statement: {
        net_cash_flow: {
          value: -3.86e9,
          unit: 'USD',
          label: 'Net Cash Flow',
          order: 1100,
        },
        net_cash_flow_from_investing_activities: {
          value: -1.4545e10,
          unit: 'USD',
          label: 'Net Cash Flow From Investing Activities',
          order: 400,
        },
        net_cash_flow_from_investing_activities_continuing: {
          value: -1.4545e10,
          unit: 'USD',
          label: 'Net Cash Flow From Investing Activities, Continuing',
          order: 500,
        },
        net_cash_flow_from_operating_activities_continuing: {
          value: 1.04038e11,
          unit: 'USD',
          label: 'Net Cash Flow From Operating Activities, Continuing',
          order: 200,
        },
        net_cash_flow_continuing: {
          value: -3.86e9,
          unit: 'USD',
          label: 'Net Cash Flow, Continuing',
          order: 1200,
        },
        net_cash_flow_from_financing_activities: {
          value: -9.3353e10,
          unit: 'USD',
          label: 'Net Cash Flow From Financing Activities',
          order: 700,
        },
        net_cash_flow_from_financing_activities_continuing: {
          value: -9.3353e10,
          unit: 'USD',
          label: 'Net Cash Flow From Financing Activities, Continuing',
          order: 800,
        },
        net_cash_flow_from_operating_activities: {
          value: 1.04038e11,
          unit: 'USD',
          label: 'Net Cash Flow From Operating Activities',
          order: 100,
        },
      },
      balance_sheet: {
        equity_attributable_to_noncontrolling_interest: {
          value: 0,
          unit: 'USD',
          label: 'Equity Attributable To Noncontrolling Interest',
          order: 1500,
        },
        current_assets: {
          value: 1.34836e11,
          unit: 'USD',
          label: 'Current Assets',
          order: 200,
        },
        other_noncurrent_assets: {
          value: 1.76726e11,
          unit: 'USD',
          label: 'Other Non-current Assets',
          order: 350,
        },
        liabilities_and_equity: {
          value: 3.51002e11,
          unit: 'USD',
          label: 'Liabilities And Equity',
          order: 1900,
        },
        noncurrent_liabilities: {
          value: 1.62431e11,
          unit: 'USD',
          label: 'Noncurrent Liabilities',
          order: 800,
        },
        fixed_assets: {
          value: 3.944e10,
          unit: 'USD',
          label: 'Fixed Assets',
          order: 320,
        },
        accounts_payable: {
          value: 5.4763e10,
          unit: 'USD',
          label: 'Accounts Payable',
          order: 710,
        },
        assets: {
          value: 3.51002e11,
          unit: 'USD',
          label: 'Assets',
          order: 100,
        },
        liabilities: {
          value: 2.87912e11,
          unit: 'USD',
          label: 'Liabilities',
          order: 600,
        },
        other_current_assets: {
          value: 1.28256e11,
          unit: 'USD',
          label: 'Other Current Assets',
          order: 250,
        },
        equity: {
          value: 6.309e10,
          unit: 'USD',
          label: 'Equity',
          order: 1400,
        },
        inventory: {
          value: 6.58e9,
          unit: 'USD',
          label: 'Inventory',
          order: 230,
        },
        other_current_liabilities: {
          value: 7.0718e10,
          unit: 'USD',
          label: 'Other Current Liabilities',
          order: 740,
        },
        current_liabilities: {
          value: 1.25481e11,
          unit: 'USD',
          label: 'Current Liabilities',
          order: 700,
        },
        noncurrent_assets: {
          value: 2.16166e11,
          unit: 'USD',
          label: 'Noncurrent Assets',
          order: 300,
        },
        equity_attributable_to_parent: {
          value: 6.309e10,
          unit: 'USD',
          label: 'Equity Attributable To Parent',
          order: 1600,
        },
      },
    },
  },
];
